// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nashoca.Infrastructure.DbContexts;

#nullable disable

namespace Nashoca.Infrastructure.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20250615141758_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Nashoca.Domain.Entities.VerbEn", b =>
                {
                    b.Property<string>("VenSymbol")
                        .HasColumnType("CHAR(5)");

                    b.Property<string>("VenAdd")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("VenExc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("VenMainF")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("VenMinF")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("VenName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("VenPastF")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("VenPpastF")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("VenPrefP")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("VenSymbol");

                    b.ToTable("VerbsEn");
                });

            modelBuilder.Entity("Nashoca.Domain.Entities.VerbTr", b =>
                {
                    b.Property<string>("VtrSymbol")
                        .HasColumnType("CHAR(5)");

                    b.Property<string>("VtrAoristS")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<int>("VtrCase")
                        .HasColumnType("int");

                    b.Property<string>("VtrChgL")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("VtrMainF")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("VtrMinF")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("VtrName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("VtrPrefP")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("VtrSymbol");

                    b.ToTable("VerbsTr");
                });

            modelBuilder.Entity("Nashoca.Domain.Entities.VerbTrans", b =>
                {
                    b.Property<string>("VtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VtEn")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("CHAR(5)");

                    b.Property<string>("VtGr")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("VtPl")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("VtRu")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("VtTr")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("CHAR(5)");

                    b.HasKey("VtId");

                    b.HasIndex("VtEn")
                        .IsUnique();

                    b.HasIndex("VtTr")
                        .IsUnique();

                    b.ToTable("VerbsTrans");
                });

            modelBuilder.Entity("Nashoca.Domain.Entities.VerbTrans", b =>
                {
                    b.HasOne("Nashoca.Domain.Entities.VerbEn", "VerbEn")
                        .WithOne("VerbTrans")
                        .HasForeignKey("Nashoca.Domain.Entities.VerbTrans", "VtEn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nashoca.Domain.Entities.VerbTr", "VerbTr")
                        .WithOne("VerbTrans")
                        .HasForeignKey("Nashoca.Domain.Entities.VerbTrans", "VtTr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VerbEn");

                    b.Navigation("VerbTr");
                });

            modelBuilder.Entity("Nashoca.Domain.Entities.VerbEn", b =>
                {
                    b.Navigation("VerbTrans");
                });

            modelBuilder.Entity("Nashoca.Domain.Entities.VerbTr", b =>
                {
                    b.Navigation("VerbTrans");
                });
#pragma warning restore 612, 618
        }
    }
}
